name: izam
version: 1.0.0+1
publish_to: 'none' 

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # Use as default SVG image loader, prefer use SVG as image asset
  flutter_svg: ^2.0.6

  # Use for State Management
  provider: ^6.0.5
  
  # Use for simplify the process of comparing instances of the same object
  equatable: ^2.0.5

  # Use for saving local data
  path: ^1.8.3
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
    
  # Use to handle screen sizes
  flutter_screenutil: ^5.8.4

  mockito: ^5.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
