name: izam
version: 1.0.0+1
publish_to: 'none' 
description: A new Flutter project.

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  # Use as default SVG image loader, prefer use SVG as image asset
  flutter_svg: ^2.0.4
  
  # Use as Network Client
  dio: ^5.0.3
  
  # Functional programming thingies
  dartz: ^0.10.1

  # Use for State Management with BLoC pattern
  provider: ^6.0.5
  equatable: ^2.0.5

  # Use as sharedPreferences to save local data
  sqflite: ^2.2.8+4
  path_provider: ^2.0.1
  
  # Use to handle screen sizes
  flutter_screenutil: ^5.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
